# Generated by Django 3.0.6 on 2020-05-20 13:05

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200515_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_url',
            field=models.CharField(default='', error_messages={'invalid': 'Invalid url', 'unique': 'A user with that username already exists.'}, help_text='Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
